name: Deploy to PRODUCTION

on:
  push:
    branches:
    - main

jobs:

  deployment:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - name: deploy to cloud
      uses: appleboy/ssh-action@master
      with:
        host: 104.131.119.143
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        command_timeout: 10m
        script: git -C /root/redd.love/main pull && docker-compose up -d --build reddlove
