name: Deploy to PRODOCTION

on:
  push:
    branches:
    - main

jobs:

  deployment:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - name: deploy to cloud
      uses: appleboy/ssh-action@master
      with:
        host: 104.131.119.143
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        command_timeout: 10m
        script: cd /root/www-data/redd.love/main && git pull && touch .deployed
